### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by GuangchuangYu** [YuLab-SMU/shinyTempSignal#7]
+ [x] 时间信号与root-to-tip距离回归线
+ [x] shiny app
+ [x] 检测outliers，并可交互选定剔除
+ [x] R包
+ [ ] 时间信号与其它数据回归？
+ [x] root-to-tip distance与其它数据回归?

这个想法，本来是基于`ggtree`和`ape`等R包，仿照`TempEst`, <https://pubmed.ncbi.nlm.nih.gov/27774300/>，写一个shiny app.

这个事情本身是挺简单的，所以计划是让本科生来完成，并希望可以由本科生独立完成一篇小文章。

那么我觉得要完成目标，还需要后面这两个，毕竟单纯仿没意思，还是需要青出于蓝而胜于蓝。而其他数据，对于`ggtree`全家桶来说，是非常容易处理的，所以后面两个实现起来，也不难。

PS：有问题，可以在github上开issue讨论，这样方便我拉其他学生进来一起讨论和解答。

**Comment by GuangchuangYu** [comment]
@xuanan-zhu 另外不要忘记剩下的两块。

**Comment by xuanan-zhu** [comment]
收到



---Original---
From: "Guangchuang ***@***.***&gt;
Date: Tue, Jan 11, 2022 13:50 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [YuLab-SMU/shinyTempSignal] TODO (#7)




 
@xuanan-zhu 另外不要忘记剩下的两块。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by GuangchuangYu** [comment]
继续搞todo list啊。

**Comment by xuanan-zhu** [comment]
嗯，谢谢老师，现在残差的时间回归算是告一段落了，还有距离的相关回归还要查查资料，斟酌一下。



---Original---
From: "Guangchuang ***@***.***&gt;
Date: Thu, Feb 24, 2022 10:04 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [YuLab-SMU/shinyTempSignal] TODO (#7)




 
继续搞todo list啊。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xuanan-zhu** [comment]
程序输入的tree可以通过计算获得 root-to-tip 距离和时间信号，然后作出回归线，求出残差，这样我们就可以完成时间信号和残差的回归，但是因为输入的数据是已经比对过然后生成的tree，差异位点的位置信息已经丢失了。
现在面临的问题是，还没找到另外一个可以与root-to-tip距离回归的数据，或许还是离不开时间信号？

**Comment by GuangchuangYu** [comment]
你去调研一下呗。

**Comment by GuangchuangYu** [comment]
不知道你调研得怎么样？

你去看一下ggtree 2017年的文章，我在文章里有一个图，是给树换枝长的。还有一个图，是用dn, ds, dn/ds和substitution rate画散点看有没有相关性的。这些例子应该能够给你一些可以用的数据，去尝试一下。

先尝试一下嘛，不离开时间可以，但你可以换枝长，那么root-to-tip distance用的就是另外的指标了嘛。

**Comment by xuanan-zhu** [comment]
谢谢老师，尝试了一下，效果还是非常明显的，分别用dn，ds，dn/ds 来更换枝长，再root-to-tip distance与时间作回归，这时候正如老师所说，换成了其他指标了。
[codeRun.pdf](https://github.com/YuLab-SMU/shinyTempSignal/files/8239256/codeRun.pdf)
。

**Comment by GuangchuangYu** [comment]
我觉得你可以一边整理代码，一边写文章，按照bioinformatics的application note来写。

**Comment by xuanan-zhu** [comment]
好的老师



---Original---
From: "Guangchuang ***@***.***&gt;
Date: Sun, Mar 13, 2022 18:14 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [YuLab-SMU/shinyTempSignal] TODO (#7)




 
我觉得你可以一边整理代码，一边写文章，按照bioinformatics的application note来写。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
